### PR TITLE
lua-parser/parser.lua: add feature for returning the detailed error

### PR DESCRIPTION
**Pull request by E-Fir**

### CODE REVIEW

**Review by andremm — APPROVED** [review]
LGTM. Thanks for the PR.

**Comment by tst2005** [comment]
Hello,
I recommend to use/load "relabel" only when `detailed_errors` is used.
```lua
if parser.detailed_errors then
      local re = require "relabel"
      local line, col = re.calcline(subject, errorpos)
```
Please make "relabel" does not become a mandatory requirement.

I'm using [pur lua implementation of `lpeg`](https://github.com/pygy/LuLPeg) but unfortunatly there is no pur lua implementation of `relabel`.
Thanks in advance

**Review by andremm — CHANGES_REQUESTED** [review]
@tst2005 thanks for your comments.

@E-Fir can you please make `relabel` not become a mandatory requirement?

Thanks

**Comment by E-Fir** [comment]
@andremm @tst2005 fixed

(sorry for the long answer, missed these replies for some reason)

**Review by andremm — APPROVED** [review]
LGTM

**Comment by E-Fir** [comment]
@andremm Would you merge it to the main branch, please?

**Comment by agladysh** [comment]
@andremm we would really like to use these changes in a released version of lua-parser — to comply with our internal policies with using only code released on luarocks in production.

Is there anything we can do to help to make a release?

**Comment by andremm** [comment]
@agladysh sorry for the delay. I just published a new version to luarocks. Please let me know if that works.

**Comment by agladysh** [comment]
@andremm No worries and many thanks!

**Comment by E-Fir** [comment]
@andremm Thank you very much!

**Pull request merged**
